spring.application.name=Code2Job

server.port=8080

# =========================================================
# GEMINI
# =========================================================

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.model=gemini-3.6-flash

spring.ai.google.genai.chat.temperature=0.3


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


# =========================================================
# THYMELEAF
# =========================================================

spring.thymeleaf.cache=false


# =========================================================
# LOGGING
# =========================================================

logging.level.com.code2job=INFO